Task05
Pogozhelskaya/formal-languages-practice pull request #6
Opened 2020-10-13 17:40 UTC by Pogozhelskaya

2020-10-14 10:06 UTC, gsvgit requested changes

2020-10-14 10:06 UTC, gsvgit commented on src/cfg_algorithms.py
> +    if gr.generate_epsilon():
Выглядит загадочно. Если Вы правильно строите рекурсивный автомат, то этой проверки не надо. У Вас просто в автомате стартовое состояние совпадёт с финальным где-то и при пересечении автоматом добавятся петли в нужных местах.

2020-10-14 11:07 UTC, Pogozhelskaya commented on src/cfg_algorithms.py
> +    if gr.generate_epsilon():
Да, стартовое с финальным совпадут, но ребро при пересечении не добавится, потому что изначально rsa так оптимизирован. Ситуацию с продукциями с пустым телом можно либо отдельно учитывать при обработке продукций в построении рекурсивного автомата, либо отдельно в конце добавлять в ответ петли. Я не обрабатываю отдельно продукции с эпсилон в правой части, потому что соответствующие петли в результирующем графе эффективнее могут быть восстановлены с помощью проверки выводимости эпсилон в грамматике, а любой путь соответствующей достижимости с такими эпсилон-петлями эквивалентен пути без них. Отдельная же обработка эпсилон-продукций в построении рекурсивного автомата влечет за собой добавление бОльшего количества единиц в матрицу тензорного произведения, что утяжеляет выполнение операции матричного умножения в транзитивном замыкании.

2020-10-15 08:16 UTC, gsvgit commented on src/cfg_algorithms.py
> +    if gr.generate_epsilon():
Да, Вы правы. Попытку снимать не буду.

2020-10-15 08:16 UTC, gsvgit approved these changes
Ок.

2020-10-15 08:20 UTC, merged